import type { DashboardLanguage } from "@/components/layout/DashboardLanguageContext";

export const dashboardCopy = {
  en: {
    common: {
      myBusiness: "My Business",
      signOut: "Sign out",
      openSidebar: "Open sidebar",
      closeSidebar: "Close sidebar",
      refresh: "Refresh",
      source: "Source",
      ruleBased: "Rule-based",
      saveChanges: "Save Changes",
      saving: "Saving...",
      mobileNumber: "Mobile Number",
    },
    nav: {
      dashboard: "Dashboard",
      history: "History",
      summary: "Summary",
      settings: "Settings",
    },
    dashboard: {
      title: "Dashboard",
      subtitle: "View any day's snapshot",
      date: "Date",
      entriesOnSelectedDay: "Entries on Selected Day",
      logSaleCard: "Log a Sale",
      addExpenseCard: "Add Expense",
      quickGuideTitle: "Quick Step-by-Step",
      quickGuideSubtitle: "Use this flow every day for cleaner records and more accurate profit.",
      quickGuideSteps: [
        "Pick the correct date first.",
        "Log each sale immediately after every transaction.",
        "Add daily expenses as they happen.",
        "Use Bulk Expense for costs that should be spread across multiple days (like rent, utilities, or advance supplies).",
        "Check Profit and Summary before closing your day.",
      ],
    },
    history: {
      title: "History",
      subtitle: "Last 30 days of activity",
      noEntries: "No entries in the last 30 days.",
      startLogging: "Start logging sales and expenses on the Dashboard!",
      sales: "Sales",
      expenses: "Expenses",
      entries: "entries",
      savedSmartSummary: "Saved Smart Summary",
      searchPlaceholder: "Search by date, label, or note",
      searchEmpty: "No entries match your search.",
    },
    summary: {
      title: "Summary",
      subtitle: "Weekly and monthly breakdown of your business",
      noData: "No data yet",
      startLogging: "Start logging sales and expenses on the Dashboard!",
      latestSaved: "Latest Saved Smart Summary",
      bestDay: "Best Day",
      worstDay: "Worst Day",
      avgDailyProfit: "Avg Daily Profit",
      acrossDays: "Across {count} days with activity",
      weekly: "Weekly",
      monthly: "Monthly",
      salesShort: "Sales",
      expensesShort: "Exp",
      expensesLong: "Expenses",
      daysActive: "{count} active days",
    },
    settings: {
      title: "Settings",
      subtitle: "Manage your account and business",
      profileHeroTitle: "Profile & Account",
      profileHeroSubtitle: "Claim your account so customers know it’s really you.",
      displayName: "Owner / Display Name",
      tagline: "Business Tagline (optional)",
      avatarColor: "Avatar Accent",
      claimStatusClaimed: "Profile claimed",
      claimStatusUnclaimed: "Profile not claimed",
      claimCta: "Claim profile",
      claimHelper: "Add your name and tagline so your reports and exports feel personal.",
      businessInfo: "Business Info",
      businessName: "Business Name",
      businessPlaceholder: "My Business",
      securityHeading: "Password & Security",
      securitySubtitle: "Update your password regularly to keep your account safe.",
      saved: "Settings saved!",
      saveFailed: "Failed to save settings",
    },
    cards: {
      todaysProfit: "Today's Profit",
      inProfit: "You're in profit today!",
      breakEven: "Break even today.",
      inNegative: "You're in the negative today.",
      totalSales: "Total Sales",
      selectedDayEntries: "{count} {label} on selected day",
      entry: "entry",
      entries: "entries",
      totalExpenses: "Total Expenses",
      more: "+{count} more",
      noExpenses: "No expenses on selected day",
      smartDailySummary: "Smart Daily Summary",
      ruleBasedFallback: "Rule-based fallback",
      aiSummaryFailed: "We could not generate the AI summary right now. Please try again shortly.",
      weeklyOverview: "7-Day Overview (ending {date})",
      profit: "Profit",
      expenses: "Expenses",
    },
    forms: {
      salesAmount: "Sales Amount",
      noteOptional: "Note (optional)",
      salesNotePlaceholder: "e.g. Morning batch, Walk-in customer...",
      logSale: "Log Sale",
      saleLogged: "Sale logged!",
      saleFailed: "Failed to log sale",
      saleFailedRetry: "Failed to log sale. Please try again.",
      amountPositive: "Amount must be greater than 0",
      labelRequired: "Label is required",
      suggestedLabels: ["Ingredients", "Groceries", "Packaging", "Gas", "Rent", "Others"],
      expenseLabel: "Label",
      expensePlaceholder: "e.g. Ingredients",
      amount: "Amount",
      addExpense: "+ Add Expense",
      expenseAdded: "Expense added!",
      expenseAddFailed: "Failed to add expense",
      expenseAddRetry: "Failed to add expense. Please try again.",
      expenseDeleteFailed: "Failed to delete expense",
      expenseRemoved: "Expense removed",
      expenseDeleteRetry: "Failed to delete expense.",
      selectedDayExpenses: "Selected Day Expenses",
      deleteExpense: "Delete {label}",
    },
    export: {
      today: "Today",
      thisWeek: "This Week",
      fullHistory: "Full History (30 days)",
      todayLabel: "Today ({date})",
      weekOf: "Week of {start} - {end}",
      last30Days: "Last 30 Days",
      noData: "No data available for the selected period.",
      exporting: "Exporting...",
    },
  },
  tl: {
    common: {
      myBusiness: "Aking Negosyo",
      signOut: "Mag-sign out",
      openSidebar: "Buksan ang sidebar",
      closeSidebar: "Isara ang sidebar",
      refresh: "I-refresh",
      source: "Pinagmulan",
      ruleBased: "Batay sa patakaran",
      saveChanges: "I-save ang mga Binago",
      saving: "Sine-save...",
      mobileNumber: "Mobile Number",
    },
    nav: {
      dashboard: "Dashboard",
      history: "Kasaysayan",
      summary: "Buod",
      settings: "Settings",
    },
    dashboard: {
      title: "Dashboard",
      subtitle: "Tingnan ang snapshot ng kahit anong araw",
      date: "Petsa",
      entriesOnSelectedDay: "Mga Entry sa Napiling Araw",
      logSaleCard: "Magtala ng Benta",
      addExpenseCard: "Magdagdag ng Gastos",
      quickGuideTitle: "Mabilis na Step-by-Step",
      quickGuideSubtitle: "Sundin ang flow na ito araw-araw para mas maayos ang records at mas accurate ang tubo.",
      quickGuideSteps: [
        "Piliin muna ang tamang petsa.",
        "Itala agad ang bawat benta pagkatapos ng bawat transaksyon.",
        "Ilagay ang arawang gastos habang nangyayari.",
        "Gamitin ang Bulk Expense para sa gastos na dapat hinahati sa maraming araw (tulad ng renta, utilities, o supplies na binili nang maramihan).",
        "Suriin ang Profit at Summary bago isara ang araw.",
      ],
    },
    history: {
      title: "Kasaysayan",
      subtitle: "Aktibidad sa nakaraang 30 araw",
      noEntries: "Walang entries sa nakaraang 30 araw.",
      startLogging: "Magsimulang magtala ng benta at gastos sa Dashboard!",
      sales: "Benta",
      expenses: "Gastos",
      entries: "entries",
      savedSmartSummary: "Naka-save na Smart Summary",
      searchPlaceholder: "Maghanap ayon sa petsa, label, o note",
      searchEmpty: "Walang tumutugma sa iyong hinanap.",
    },
    summary: {
      title: "Buod",
      subtitle: "Lingguhan at buwanang breakdown ng negosyo mo",
      noData: "Wala pang data",
      startLogging: "Magsimulang magtala ng benta at gastos sa Dashboard!",
      latestSaved: "Pinakabagong Naka-save na Smart Summary",
      bestDay: "Pinakamagandang Araw",
      worstDay: "Pinakamahinang Araw",
      avgDailyProfit: "Karaniwang Tubo Kada Araw",
      acrossDays: "Sa loob ng {count} araw na may aktibidad",
      weekly: "Lingguhan",
      monthly: "Buwanan",
      salesShort: "Benta",
      expensesShort: "Gast",
      expensesLong: "Gastos",
      daysActive: "{count} araw na may aktibidad",
    },
    settings: {
      title: "Settings",
      subtitle: "Pamahalaan ang account at negosyo mo",
      profileHeroTitle: "Profile at Account",
      profileHeroSubtitle: "I-claim ang account mo para malaman ng customers na ikaw ito.",
      displayName: "Pangalan ng May-ari",
      tagline: "Tagline ng Negosyo (opsyonal)",
      avatarColor: "Avatar Accent",
      claimStatusClaimed: "Na-claim na ang profile",
      claimStatusUnclaimed: "Hindi pa na-claim ang profile",
      claimCta: "I-claim ang profile",
      claimHelper: "Idagdag ang pangalan at tagline para mas personal ang reports at exports mo.",
      businessInfo: "Impormasyon ng Negosyo",
      businessName: "Pangalan ng Negosyo",
      businessPlaceholder: "Aking Negosyo",
      securityHeading: "Password at Seguridad",
      securitySubtitle: "Regular na i-update ang password para protektado ang account mo.",
      saved: "Na-save ang settings!",
      saveFailed: "Hindi na-save ang settings",
    },
    cards: {
      todaysProfit: "Tubo Ngayon",
      inProfit: "Kumikita ka ngayong araw!",
      breakEven: "Tabla ka ngayong araw.",
      inNegative: "Lugi ka ngayong araw.",
      totalSales: "Kabuuang Benta",
      selectedDayEntries: "{count} {label} sa napiling araw",
      entry: "entry",
      entries: "entries",
      totalExpenses: "Kabuuang Gastos",
      more: "+{count} pa",
      noExpenses: "Walang gastos sa napiling araw",
      smartDailySummary: "Smart Daily Summary",
      ruleBasedFallback: "Fallback na batay sa patakaran",
      aiSummaryFailed: "Hindi namin magawa ang AI summary ngayon. Pakisubukang muli mamaya.",
      weeklyOverview: "7-Araw na Overview (hanggang {date})",
      profit: "Tubo",
      expenses: "Gastos",
    },
    forms: {
      salesAmount: "Halaga ng Benta",
      noteOptional: "Note (optional)",
      salesNotePlaceholder: "hal. Pang-umagang batch, walk-in customer...",
      logSale: "Itala ang Benta",
      saleLogged: "Naitala ang benta!",
      saleFailed: "Hindi naitala ang benta",
      saleFailedRetry: "Hindi naitala ang benta. Pakisubukang muli.",
      amountPositive: "Dapat mas mataas sa 0 ang halaga",
      labelRequired: "Kailangan ang label",
      suggestedLabels: ["Sangkap", "Groceries", "Packaging", "Gas", "Renta", "Iba pa"],
      expenseLabel: "Label",
      expensePlaceholder: "hal. Sangkap",
      amount: "Halaga",
      addExpense: "+ Magdagdag ng Gastos",
      expenseAdded: "Naidagdag ang gastos!",
      expenseAddFailed: "Hindi naidagdag ang gastos",
      expenseAddRetry: "Hindi naidagdag ang gastos. Pakisubukang muli.",
      expenseDeleteFailed: "Hindi natanggal ang gastos",
      expenseRemoved: "Natanggal ang gastos",
      expenseDeleteRetry: "Hindi natanggal ang gastos.",
      selectedDayExpenses: "Mga Gastos sa Napiling Araw",
      deleteExpense: "Burahin ang {label}",
    },
    export: {
      today: "Ngayon",
      thisWeek: "Ngayong Linggo",
      fullHistory: "Buong Kasaysayan (30 araw)",
      todayLabel: "Ngayon ({date})",
      weekOf: "Linggo ng {start} - {end}",
      last30Days: "Huling 30 Araw",
      noData: "Walang available na data para sa napiling period.",
      exporting: "Ini-export...",
    },
  },
} as const;

export function getDashboardCopy(language: DashboardLanguage) {
  return dashboardCopy[language];
}

export function interpolate(template: string, values: Record<string, string | number>) {
  return Object.entries(values).reduce(
    (message, [key, value]) => message.replace(`{${key}}`, String(value)),
    template
  );
}
