import type { DashboardLanguage } from "@/components/layout/DashboardLanguageContext";

export const dashboardCopy = {
  en: {
    common: {
      myBusiness: "My Business",
      signOut: "Sign out",
      openSidebar: "Open sidebar",
      closeSidebar: "Close sidebar",
      refresh: "Refresh",
      source: "Source",
      ruleBased: "Rule-based",
      saveChanges: "Save Changes",
      saving: "Saving...",
      mobileNumber: "Mobile Number",
    },
    nav: {
      dashboard: "Dashboard",
      history: "History",
      summary: "Summary",
      settings: "Settings",
    },
    dashboard: {
      title: "Dashboard",
      subtitle: "View any day's snapshot",
      date: "Date",
      entriesOnSelectedDay: "Entries on Selected Day",
      logSaleCard: "Log a Sale",
      addExpenseCard: "Add Expense",
    },
    history: {
      title: "History",
      subtitle: "Last 30 days of activity",
      noEntries: "No entries in the last 30 days.",
      startLogging: "Start logging sales and expenses on the Dashboard!",
      sales: "Sales",
      expenses: "Expenses",
      entries: "entries",
      savedSmartSummary: "Saved Smart Summary",
    },
    summary: {
      title: "Summary",
      subtitle: "Weekly and monthly breakdown of your business",
      noData: "No data yet",
      startLogging: "Start logging sales and expenses on the Dashboard!",
      latestSaved: "Latest Saved Smart Summary",
      bestDay: "Best Day",
      worstDay: "Worst Day",
      avgDailyProfit: "Avg Daily Profit",
      acrossDays: "Across {count} days with activity",
      weekly: "Weekly",
      monthly: "Monthly",
      salesShort: "Sales",
      expensesShort: "Exp",
      expensesLong: "Expenses",
      daysActive: "{count} active days",
    },
    settings: {
      title: "Settings",
      subtitle: "Manage your account and business",
      businessInfo: "Business Info",
      businessName: "Business Name",
      businessPlaceholder: "My Business",
      saved: "Settings saved!",
      saveFailed: "Failed to save settings",
    },
    cards: {
      todaysProfit: "Today's Profit",
      inProfit: "You're in profit today!",
      breakEven: "Break even today.",
      inNegative: "You're in the negative today.",
      totalSales: "Total Sales",
      selectedDayEntries: "{count} {label} on selected day",
      entry: "entry",
      entries: "entries",
      totalExpenses: "Total Expenses",
      more: "+{count} more",
      noExpenses: "No expenses on selected day",
      smartDailySummary: "Smart Daily Summary",
      ruleBasedFallback: "Rule-based fallback",
      aiSummaryFailed: "We could not generate the AI summary right now. Please try again shortly.",
      weeklyOverview: "7-Day Overview (ending {date})",
      profit: "Profit",
      expenses: "Expenses",
    },
    forms: {
      salesAmount: "Sales Amount",
      noteOptional: "Note (optional)",
      salesNotePlaceholder: "e.g. Morning batch, Walk-in customer...",
      logSale: "Log Sale",
      saleLogged: "Sale logged!",
      saleFailed: "Failed to log sale",
      saleFailedRetry: "Failed to log sale. Please try again.",
      amountPositive: "Amount must be greater than 0",
      labelRequired: "Label is required",
      suggestedLabels: ["Ingredients", "Packaging", "Gas", "Rent", "Others"],
      expenseLabel: "Label",
      expensePlaceholder: "e.g. Ingredients",
      amount: "Amount",
      addExpense: "+ Add Expense",
      expenseAdded: "Expense added!",
      expenseAddFailed: "Failed to add expense",
      expenseAddRetry: "Failed to add expense. Please try again.",
      expenseDeleteFailed: "Failed to delete expense",
      expenseRemoved: "Expense removed",
      expenseDeleteRetry: "Failed to delete expense.",
      selectedDayExpenses: "Selected Day Expenses",
      deleteExpense: "Delete {label}",
    },
    export: {
      today: "Today",
      thisWeek: "This Week",
      fullHistory: "Full History (30 days)",
      todayLabel: "Today ({date})",
      weekOf: "Week of {start} - {end}",
      last30Days: "Last 30 Days",
      noData: "No data available for the selected period.",
      exporting: "Exporting...",
    },
  },
  tl: {
    common: {
      myBusiness: "Aking Negosyo",
      signOut: "Mag-sign out",
      openSidebar: "Buksan ang sidebar",
      closeSidebar: "Isara ang sidebar",
      refresh: "I-refresh",
      source: "Pinagmulan",
      ruleBased: "Batay sa patakaran",
      saveChanges: "I-save ang mga Binago",
      saving: "Sine-save...",
      mobileNumber: "Mobile Number",
    },
    nav: {
      dashboard: "Dashboard",
      history: "Kasaysayan",
      summary: "Buod",
      settings: "Settings",
    },
    dashboard: {
      title: "Dashboard",
      subtitle: "Tingnan ang snapshot ng kahit anong araw",
      date: "Petsa",
      entriesOnSelectedDay: "Mga Entry sa Napiling Araw",
      logSaleCard: "Magtala ng Benta",
      addExpenseCard: "Magdagdag ng Gastos",
    },
    history: {
      title: "Kasaysayan",
      subtitle: "Aktibidad sa nakaraang 30 araw",
      noEntries: "Walang entries sa nakaraang 30 araw.",
      startLogging: "Magsimulang magtala ng benta at gastos sa Dashboard!",
      sales: "Benta",
      expenses: "Gastos",
      entries: "entries",
      savedSmartSummary: "Naka-save na Smart Summary",
    },
    summary: {
      title: "Buod",
      subtitle: "Lingguhan at buwanang breakdown ng negosyo mo",
      noData: "Wala pang data",
      startLogging: "Magsimulang magtala ng benta at gastos sa Dashboard!",
      latestSaved: "Pinakabagong Naka-save na Smart Summary",
      bestDay: "Pinakamagandang Araw",
      worstDay: "Pinakamahinang Araw",
      avgDailyProfit: "Karaniwang Tubo Kada Araw",
      acrossDays: "Sa loob ng {count} araw na may aktibidad",
      weekly: "Lingguhan",
      monthly: "Buwanan",
      salesShort: "Benta",
      expensesShort: "Gast",
      expensesLong: "Gastos",
      daysActive: "{count} araw na may aktibidad",
    },
    settings: {
      title: "Settings",
      subtitle: "Pamahalaan ang account at negosyo mo",
      businessInfo: "Impormasyon ng Negosyo",
      businessName: "Pangalan ng Negosyo",
      businessPlaceholder: "Aking Negosyo",
      saved: "Na-save ang settings!",
      saveFailed: "Hindi na-save ang settings",
    },
    cards: {
      todaysProfit: "Tubo Ngayon",
      inProfit: "Kumikita ka ngayong araw!",
      breakEven: "Tabla ka ngayong araw.",
      inNegative: "Lugi ka ngayong araw.",
      totalSales: "Kabuuang Benta",
      selectedDayEntries: "{count} {label} sa napiling araw",
      entry: "entry",
      entries: "entries",
      totalExpenses: "Kabuuang Gastos",
      more: "+{count} pa",
      noExpenses: "Walang gastos sa napiling araw",
      smartDailySummary: "Smart Daily Summary",
      ruleBasedFallback: "Fallback na batay sa patakaran",
      aiSummaryFailed: "Hindi namin magawa ang AI summary ngayon. Pakisubukang muli mamaya.",
      weeklyOverview: "7-Araw na Overview (hanggang {date})",
      profit: "Tubo",
      expenses: "Gastos",
    },
    forms: {
      salesAmount: "Halaga ng Benta",
      noteOptional: "Note (optional)",
      salesNotePlaceholder: "hal. Pang-umagang batch, walk-in customer...",
      logSale: "Itala ang Benta",
      saleLogged: "Naitala ang benta!",
      saleFailed: "Hindi naitala ang benta",
      saleFailedRetry: "Hindi naitala ang benta. Pakisubukang muli.",
      amountPositive: "Dapat mas mataas sa 0 ang halaga",
      labelRequired: "Kailangan ang label",
      suggestedLabels: ["Sangkap", "Packaging", "Gas", "Renta", "Iba pa"],
      expenseLabel: "Label",
      expensePlaceholder: "hal. Sangkap",
      amount: "Halaga",
      addExpense: "+ Magdagdag ng Gastos",
      expenseAdded: "Naidagdag ang gastos!",
      expenseAddFailed: "Hindi naidagdag ang gastos",
      expenseAddRetry: "Hindi naidagdag ang gastos. Pakisubukang muli.",
      expenseDeleteFailed: "Hindi natanggal ang gastos",
      expenseRemoved: "Natanggal ang gastos",
      expenseDeleteRetry: "Hindi natanggal ang gastos.",
      selectedDayExpenses: "Mga Gastos sa Napiling Araw",
      deleteExpense: "Burahin ang {label}",
    },
    export: {
      today: "Ngayon",
      thisWeek: "Ngayong Linggo",
      fullHistory: "Buong Kasaysayan (30 araw)",
      todayLabel: "Ngayon ({date})",
      weekOf: "Linggo ng {start} - {end}",
      last30Days: "Huling 30 Araw",
      noData: "Walang available na data para sa napiling period.",
      exporting: "Ini-export...",
    },
  },
} as const;

export function getDashboardCopy(language: DashboardLanguage) {
  return dashboardCopy[language];
}

export function interpolate(template: string, values: Record<string, string | number>) {
  return Object.entries(values).reduce(
    (message, [key, value]) => message.replace(`{${key}}`, String(value)),
    template
  );
}